<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $schools = [
            [
                'name' => 'St. Michael\'s Choir School',
                'slug' => 'st-michaels-choir-school',
                'description' => 'St. Michael\'s Choir School is a Catholic elementary and secondary school in Toronto, known for its exceptional choral program and academic excellence.',
                'address' => '65 Bond Street',
                'city' => 'Toronto',
                'province' => 'Ontario',
                'postal_code' => 'M5B 1X5',
                'phone' => '(416) 393-5518',
                'email' => 'info@smcs.on.ca',
                'website_url' => 'https://www.tcdsb.org/schools/stmichaelschoirschool',
                'latitude' => 43.6572,
                'longitude' => -79.3786,
                'school_type' => 'catholic',
                'grade_level' => 'k-12',
                'school_board' => 'Toronto Catholic District School Board',
                'principal_name' => 'Michael Sheedy',
                'student_capacity' => 350,
                'established_year' => 1937,
                'rating' => 4.5,
                'programs' => json_encode(['Music Program', 'Arts', 'Athletics', 'STEM']),
                'languages' => json_encode(['English', 'French', 'Latin']),
                'facilities' => json_encode(['Music Rooms', 'Chapel', 'Gymnasium', 'Library', 'Science Labs']),
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Jarvis Collegiate Institute',
                'slug' => 'jarvis-collegiate-institute',
                'description' => 'Jarvis Collegiate Institute is a public secondary school in downtown Toronto, offering comprehensive academic and extracurricular programs.',
                'address' => '495 Jarvis Street',
                'city' => 'Toronto',
                'province' => 'Ontario',
                'postal_code' => 'M4Y 2G8',
                'phone' => '(416) 393-0140',
                'email' => 'jarvis@tdsb.on.ca',
                'website_url' => 'https://schoolweb.tdsb.on.ca/jarvisci',
                'latitude' => 43.6677,
                'longitude' => -79.3766,
                'school_type' => 'public',
                'grade_level' => 'secondary',
                'school_board' => 'Toronto District School Board',
                'principal_name' => 'Elizabeth Taylor',
                'student_capacity' => 900,
                'established_year' => 1807,
                'rating' => 4.2,
                'programs' => json_encode(['Advanced Placement', 'Arts', 'Athletics', 'STEM', 'French Immersion']),
                'languages' => json_encode(['English', 'French']),
                'facilities' => json_encode(['Auditorium', 'Gymnasium', 'Library', 'Science Labs', 'Computer Labs', 'Art Studios']),
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Lord Lansdowne Public School',
                'slug' => 'lord-lansdowne-public-school',
                'description' => 'Lord Lansdowne Public School is an elementary school serving the downtown Toronto community with a focus on inclusive education.',
                'address' => '33 Robert Street',
                'city' => 'Toronto',
                'province' => 'Ontario',
                'postal_code' => 'M5S 2K3',
                'phone' => '(416) 393-9410',
                'email' => 'lordlansdowne@tdsb.on.ca',
                'website_url' => 'https://schoolweb.tdsb.on.ca/lordlansdowne',
                'latitude' => 43.6612,
                'longitude' => -79.3999,
                'school_type' => 'public',
                'grade_level' => 'elementary',
                'school_board' => 'Toronto District School Board',
                'principal_name' => 'Sarah Johnson',
                'student_capacity' => 500,
                'established_year' => 1888,
                'rating' => 4.0,
                'programs' => json_encode(['Extended French', 'Arts', 'Athletics', 'Special Education']),
                'languages' => json_encode(['English', 'French']),
                'facilities' => json_encode(['Gymnasium', 'Library', 'Computer Lab', 'Playground', 'Music Room']),
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Ryerson Community School',
                'slug' => 'ryerson-community-school',
                'description' => 'Ryerson Community School is a diverse elementary school in downtown Toronto, known for its strong community partnerships.',
                'address' => '96 Denison Avenue',
                'city' => 'Toronto',
                'province' => 'Ontario',
                'postal_code' => 'M5T 1B5',
                'phone' => '(416) 393-0570',
                'email' => 'ryerson@tdsb.on.ca',
                'website_url' => 'https://schoolweb.tdsb.on.ca/ryerson',
                'latitude' => 43.6483,
                'longitude' => -79.4003,
                'school_type' => 'public',
                'grade_level' => 'elementary',
                'school_board' => 'Toronto District School Board',
                'principal_name' => 'Michael Chen',
                'student_capacity' => 450,
                'established_year' => 1876,
                'rating' => 3.8,
                'programs' => json_encode(['Arts', 'Athletics', 'ESL Support', 'After School Programs']),
                'languages' => json_encode(['English', 'Mandarin', 'Cantonese']),
                'facilities' => json_encode(['Gymnasium', 'Library', 'Computer Lab', 'Playground']),
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'The Bishop Strachan School',
                'slug' => 'bishop-strachan-school',
                'description' => 'The Bishop Strachan School is an independent day and boarding school for girls, offering exceptional education from JK to Grade 12.',
                'address' => '298 Lonsdale Road',
                'city' => 'Toronto',
                'province' => 'Ontario',
                'postal_code' => 'M4V 1X2',
                'phone' => '(416) 483-4325',
                'email' => 'info@bss.on.ca',
                'website_url' => 'https://www.bss.on.ca',
                'latitude' => 43.6917,
                'longitude' => -79.3947,
                'school_type' => 'private',
                'grade_level' => 'k-12',
                'school_board' => 'Independent',
                'principal_name' => 'Dr. Angela Terpstra',
                'student_capacity' => 900,
                'established_year' => 1867,
                'rating' => 4.8,
                'programs' => json_encode(['IB Programme', 'Advanced Placement', 'Arts', 'Athletics', 'STEM', 'Leadership']),
                'languages' => json_encode(['English', 'French', 'Spanish', 'Mandarin']),
                'facilities' => json_encode(['Athletic Centre', 'Swimming Pool', 'Theatre', 'Science Centre', 'Art Studios', 'Boarding Facilities']),
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'University of Toronto Schools',
                'slug' => 'university-of-toronto-schools',
                'description' => 'UTS is a university-preparatory school affiliated with the University of Toronto, known for academic excellence.',
                'address' => '371 Bloor Street West',
                'city' => 'Toronto',
                'province' => 'Ontario',
                'postal_code' => 'M5S 2R7',
                'phone' => '(416) 978-2011',
                'email' => 'info@utschools.ca',
                'website_url' => 'https://www.utschools.ca',
                'latitude' => 43.6645,
                'longitude' => -79.4071,
                'school_type' => 'private',
                'grade_level' => 'secondary',
                'school_board' => 'University of Toronto',
                'principal_name' => 'Rosemary Evans',
                'student_capacity' => 675,
                'established_year' => 1910,
                'rating' => 4.9,
                'programs' => json_encode(['Advanced Placement', 'STEM', 'Arts', 'Athletics', 'Research Programs']),
                'languages' => json_encode(['English', 'French', 'Latin', 'Spanish']),
                'facilities' => json_encode(['Science Labs', 'Computer Labs', 'Library', 'Gymnasium', 'Music Rooms']),
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'King Edward Public School',
                'slug' => 'king-edward-public-school',
                'description' => 'King Edward Public School serves the diverse downtown Toronto community with quality elementary education.',
                'address' => '112 Lippincott Street',
                'city' => 'Toronto',
                'province' => 'Ontario',
                'postal_code' => 'M5S 2P1',
                'phone' => '(416) 393-9335',
                'email' => 'kingedward@tdsb.on.ca',
                'website_url' => 'https://schoolweb.tdsb.on.ca/kingedward',
                'latitude' => 43.6568,
                'longitude' => -79.4079,
                'school_type' => 'public',
                'grade_level' => 'elementary',
                'school_board' => 'Toronto District School Board',
                'principal_name' => 'Jennifer Martinez',
                'student_capacity' => 400,
                'established_year' => 1874,
                'rating' => 3.9,
                'programs' => json_encode(['French Immersion', 'Arts', 'Special Education Support']),
                'languages' => json_encode(['English', 'French']),
                'facilities' => json_encode(['Gymnasium', 'Library', 'Computer Lab', 'Playground']),
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Central Technical School',
                'slug' => 'central-technical-school',
                'description' => 'Central Technical School is a composite school offering both academic and technical programs in downtown Toronto.',
                'address' => '725 Bathurst Street',
                'city' => 'Toronto',
                'province' => 'Ontario',
                'postal_code' => 'M5S 2R5',
                'phone' => '(416) 393-0060',
                'email' => 'centraltech@tdsb.on.ca',
                'website_url' => 'https://schoolweb.tdsb.on.ca/centraltech',
                'latitude' => 43.6629,
                'longitude' => -79.4112,
                'school_type' => 'public',
                'grade_level' => 'secondary',
                'school_board' => 'Toronto District School Board',
                'principal_name' => 'Robert Thompson',
                'student_capacity' => 1500,
                'established_year' => 1915,
                'rating' => 4.1,
                'programs' => json_encode(['Technical Programs', 'Arts', 'Athletics', 'STEM', 'Co-op']),
                'languages' => json_encode(['English', 'French']),
                'facilities' => json_encode(['Tech Shops', 'Gymnasium', 'Pool', 'Theatre', 'Science Labs']),
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Harbord Collegiate Institute',
                'slug' => 'harbord-collegiate-institute',
                'description' => 'Harbord Collegiate Institute is a historic secondary school known for its academic excellence and diverse programs.',
                'address' => '286 Harbord Street',
                'city' => 'Toronto',
                'province' => 'Ontario',
                'postal_code' => 'M6G 1G5',
                'phone' => '(416) 393-1650',
                'email' => 'harbord@tdsb.on.ca',
                'website_url' => 'https://schoolweb.tdsb.on.ca/harbordci',
                'latitude' => 43.6607,
                'longitude' => -79.4151,
                'school_type' => 'public',
                'grade_level' => 'secondary',
                'school_board' => 'Toronto District School Board',
                'principal_name' => 'Steve Yee',
                'student_capacity' => 1000,
                'established_year' => 1892,
                'rating' => 4.3,
                'programs' => json_encode(['French Immersion', 'AP Courses', 'Arts', 'Athletics', 'STEM']),
                'languages' => json_encode(['English', 'French']),
                'facilities' => json_encode(['Gymnasium', 'Library', 'Science Labs', 'Computer Labs', 'Music Rooms']),
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Orde Street Public School',
                'slug' => 'orde-street-public-school',
                'description' => 'Orde Street Public School is a vibrant elementary school serving the downtown Toronto community.',
                'address' => '18 Orde Street',
                'city' => 'Toronto',
                'province' => 'Ontario',
                'postal_code' => 'M5T 1P6',
                'phone' => '(416) 393-9830',
                'email' => 'ordestreet@tdsb.on.ca',
                'website_url' => 'https://schoolweb.tdsb.on.ca/ordestreet',
                'latitude' => 43.6548,
                'longitude' => -79.3945,
                'school_type' => 'public',
                'grade_level' => 'elementary',
                'school_board' => 'Toronto District School Board',
                'principal_name' => 'David Lee',
                'student_capacity' => 350,
                'established_year' => 1959,
                'rating' => 3.7,
                'programs' => json_encode(['Extended French', 'Arts', 'Music', 'Athletics']),
                'languages' => json_encode(['English', 'French']),
                'facilities' => json_encode(['Gymnasium', 'Library', 'Computer Lab', 'Playground']),
                'is_active' => true,
                'is_featured' => false,
            ],
        ];

        foreach ($schools as $school) {
            $school['created_at'] = now();
            $school['updated_at'] = now();
            DB::table('schools')->insertOrIgnore($school);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $schoolSlugs = [
            'st-michaels-choir-school',
            'jarvis-collegiate-institute',
            'lord-lansdowne-public-school',
            'ryerson-community-school',
            'bishop-strachan-school',
            'university-of-toronto-schools',
            'king-edward-public-school',
            'central-technical-school',
            'harbord-collegiate-institute',
            'orde-street-public-school',
        ];
        
        DB::table('schools')->whereIn('slug', $schoolSlugs)->delete();
    }
};